# Generated by Django 2.2.1 on 2019-06-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190606_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='delivery_available',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='information',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='google',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('visa', 'Visa'), ('both', 'Both')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='pinterest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='work_end_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='work_end_period',
            field=models.CharField(blank=True, choices=[('am', 'AM'), ('pm', 'PM')], default='pm', max_length=20),
        ),
        migrations.AlterField(
            model_name='information',
            name='work_start_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='work_start_period',
            field=models.CharField(blank=True, choices=[('am', 'AM'), ('pm', 'PM')], default='am', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images'),
        ),
    ]
